global:
  resolve_timeout: 5m

route:
  group_by: ['alert']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'slack'
  routes:
    - match:
        severity: 'critical'
      receiver: 'pagerduty'
      group_wait: 10s
      repeat_interval: 1h
    - match:
        severity: 'warning'
      receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - channel: '#monitoring-alerts'
        api_url: '${SLACK_WEBHOOK_URL}'  # Set via env var
        send_resolved: true
        icon_url: 'https://avatars3.githubusercontent.com/u/3380462'
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
          *Description:* {{ .Annotations.description }}
          *Duration:* {{ .Duration }}
          *Grafana:* <{{ .Annotations.grafana_url }}|View Dashboard>
          {{ end }}

  - name: 'pagerduty'
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'  # Set via env var
        send_resolved: true
        description: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
        client: 'alertmanager'
        client_url: '{{ template "pagerduty.default.clientURL" . }}'
        details:
          firing: '{{ template "pagerduty.default.instances" .Alerts.Firing }}'
          resolved: '{{ template "pagerduty.default.instances" .Alerts.Resolved }}'
          num_firing: '{{ .Alerts.Firing | len }}'
