"""add work_items table

Revision ID: ca877e32a459
Revises: 5311c1cffac8
Create Date: 2025-09-17 15:21:53.096273

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca877e32a459"
down_revision: Union[str, Sequence[str], None] = "5311c1cffac8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "work_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("sprint_id", sa.UUID(), nullable=True),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("assignee_id", sa.UUID(), nullable=True),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("priority", sa.Float(), nullable=False),
        sa.Column("story_points", sa.Integer(), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_sprint_id_for_action_item", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["assignee_id"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_items_id"), "work_items", ["id"], unique=False)
    op.create_index(
        op.f("ix_work_items_priority"), "work_items", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_work_items_status"), "work_items", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_work_items_team_id"), "work_items", ["team_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_work_items_team_id"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_status"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_priority"), table_name="work_items")
    op.drop_index(op.f("ix_work_items_id"), table_name="work_items")
    op.drop_table("work_items")
    # ### end Alembic commands ###
