version: '3.8'

services:
  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: sprintsense
      POSTGRES_PASSWORD: sprintsense
      POSTGRES_DB: sprintsense
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sprintsense"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=sprintsense
      - POSTGRES_PASSWORD=sprintsense
      - POSTGRES_DB=sprintsense
      - POSTGRES_PORT=5432
      - ENVIRONMENT=development
      - LOG_LEVEL=INFO
      - BACKEND_CORS_ORIGINS=http://localhost:5173,http://localhost:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../backend:/app
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  postgres_data: