name: CodeRabbit Review

# Note: CodeRabbit Pro provides automated reviews via GitHub App integration.
# This workflow serves as a placeholder and status check.
# To enable CodeRabbit Pro reviews:
# 1. Install the CodeRabbit GitHub App from https://github.com/marketplace/coderabbitai
# 2. Configure repository access
# 3. CodeRabbit will automatically review PRs and provide suggestions

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main, develop]
  push:
    branches: [main, develop]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'
      - 'docs/**'
      - '**/*.py'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'

# Prevent concurrent runs for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Status check and configuration validation
  coderabbit-status:
    name: CodeRabbit Integration Status
    runs-on: ubuntu-latest

    # Skip draft PRs unless configured otherwise
    if: >
      (github.event_name == 'push') ||
      (github.event_name == 'pull_request' && github.event.pull_request.draft == false)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: CodeRabbit Integration Check
        run: |
          echo "🤖 CodeRabbit Integration Status"
          echo "======================================"
          echo ""
          echo "✅ CodeRabbit Pro GitHub App should be installed for automated reviews"
          echo "📝 Configuration file: .coderabbit.yml (checking...)"
          echo "🔧 MCP integration: Available in Warp terminal"
          echo ""
          echo "To complete setup:"
          echo "1. Install CodeRabbit GitHub App: https://github.com/marketplace/coderabbitai"
          echo "2. Grant repository access to SprintSense"
          echo "3. CodeRabbit will automatically review PRs and commits"
          echo ""
          echo "Manual reviews available via Warp MCP integration"

      - name: Validate CodeRabbit Configuration
        run: |
          if [ -f ".coderabbit.yml" ]; then
            echo "✅ CodeRabbit configuration file found"
            echo ""
            echo "Configuration preview:"
            echo "======================"
            head -20 .coderabbit.yml
          else
            echo "❌ CodeRabbit configuration file missing"
            echo "Expected location: .coderabbit.yml"
            exit 1
          fi

      - name: Integration Summary
        run: |
          echo ""
          echo "📋 Integration Summary"
          echo "====================="
          echo "• Configuration: ✅ Ready"
          echo "• Warp MCP: ✅ Configured"
          echo "• GitHub App: ⏳ Needs installation"
          echo ""
          echo "🎯 Next Steps:"
          echo "1. Visit: https://github.com/marketplace/coderabbitai"
          echo "2. Install the app for hazlamahedich/SprintSense"
          echo "3. Reviews will appear automatically on PRs"
